# Lab 3 Template

**Author:** [YOUR NAME]

**Course:** Physics 434 - Data Analysis Lab  

In this laboratory we will practice Monte Carlo integration methods and implement the Ising model. We'll explore how statistical methods can be used to solve complex physical problems numerically.

## Key Concepts
- Monte Carlo integration -- rejection method
- Statistical sampling and uncertainty
- Ising model and phase transitions
- Metropolis algorithm -- probability condition


## Import Libraries

**TODO:** Import necessary libraries for this lab.

In [ ]:
# TODO: Import numpy, matplotlib.pyplot, and any other necessary libraries
# Set numpy random seed for reproducibility

# import numpy as np
# import matplotlib.pyplot as plt
# np.random.seed(42)

# Part I: Sphere in 3D Monte Carlo Integration

We will use Monte Carlo methods to calculate the mass of a sphere with different density distributions. The basic idea is to:
1. Generate random points in a cube that encloses the sphere
2. Check which points fall inside the sphere
3. Use these points to estimate integrals

## Part A: Uniform Density (3 pt)

For a sphere of radius 1 with uniform density ρ = 2.0, calculate the mass using Monte Carlo integration.

**Monte Carlo Integration Theory:**

Monte Carlo integration is a powerful numerical technique that uses random sampling to estimate integrals. For a 3D sphere problem, we:

1. **Enclosing Volume**: Use a cube from [-1,1]³ (volume = 8) that contains the unit sphere
2. **Random Sampling**: Generate N random points uniformly distributed in this cube
3. **Hit-or-Miss**: Check which points fall inside the sphere (x² + y² + z² < 1)
4. **Integration Formula**: Estimate the integral using:
   $$\text{Mass} = V_{cube} \times \frac{1}{N} \sum_{i=1}^{N} \rho(x_i, y_i, z_i) \times I(x_i, y_i, z_i)$$
   where I(x,y,z) = 1 if point is inside sphere, 0 otherwise

**Statistical Uncertainty:**
- Standard error decreases as σ ∝ 1/√N (slow convergence!)
- Uncertainty estimate: σ ≈ np.sqrt(p * (1 - p) / N) * cube_volume * density, where p is fraction of acceptance.
- For uniform distribution in [-1,1]: np.sqrt(p * (1 - p)) = √((1-(-1))²/12) = √(1/3) ≈ 0.577
check if it's true.


In [ ]:
# TODO: Step 1 - Generate random points function
# Use np.random.uniform(-1.0, 1.0, N) for each coordinate

# TODO: Step 2 - Index function for sphere  
# Check condition: x² + y² + z² < 1

# TODO: Step 3 - Uniform density function
# Return constant density = 2.0 for all points

# TODO: Step 4 - Mass calculation with uncertainty
# Apply Monte Carlo formula: V_cube/N * sum(density * inside)
# Calculate uncertainty: V_cube * 0.577 / sqrt(N)

# TODO: Test with N=100 and print results

# print(f'Mass estimate (N=100): {mass_100:.3f} ± {uncertainty_100:.3f}')
# print(f'Theoretical value: {theoretical:.3f}')
# print(f'Relative error: {abs(mass_100 - theoretical)/theoretical * 100:.1f}%')

**Convergence Analysis:**

Study how Monte Carlo estimates improve with more samples (N).

**Key Concepts:**
- Error decreases as 1/√N (slow convergence)

In [ ]:
# TODO: Convergence analysis implementation
# Create N_values array from 100 to 100,000

# N_values = np.linspace(100, 100000, 100, dtype=int)
# masses = []
# uncertainties = []

# TODO: Loop over N values and collect mass estimates and uncertainties


# TODO: Create 2 figure with two subplots: convergence plot and uncertainty scaling to 1/√N 

# ax1.scatter(N_values, masses, label='MC estimates' ...
# ax1.fill_between(N_values, masses - uncertainties, masses + uncertainties ...
# ax2.loglog(N_values, uncertainties ...
# theoretical_scaling = uncertainties[0] * np.sqrt(N_values[0] / N_values)
# ax2.loglog(N_values, theoretical_scaling ...

# TODO: Print results

# final_error = abs(masses[-1] - theoretical) / theoretical * 100
# print(f"\nFinal results (N={N_values[-1]}):")
# print(f"Mass: {masses[-1]:.4f} ± {uncertainties[-1]:.4f}")
# print(f"Relative error: {final_error:.2f}%")

## Part B: Linear Density (3 pt)

**Variable Density:** ρ(r) = ρ₀r where r = √(x² + y² + z²)

**Theory:** 
- Density increases with distance from center
- Analytical result: M = πρ₀ = 2π ≈ 6.283
- Same Monte Carlo method, different density function

**Requirements:**
- Implement `linear_density(x, y, z)` function  
- Find N needed for 1% accuracy you can use scaling 
- Compare with theoretical value

In [ ]:
# TODO: Implement linear density function
# Calculate r = sqrt(x² + y² + z²), then return ρ₀ × r

# TODO: Find N for 1% accuracy
# Use scaling relationship: N_new = N_old × (σ_old / σ_target)²

# TODO: Calculate mass with linear density large N
# Compare with theoretical value 

# print(f"\nFor 1% accuracy:")
# print(f"Target uncertainty: {target_uncertainty:.4f}")
# print(f"Required N: {N_1_percent:.0f}")

# print(f"Verification: mass = {mass_1p:.4f} ± {unc_1p:.4f}")
# print(f"Actual error: {actual_error:.2f}%")

## Bonus 1: Exponential Density (1 pt)

Consider a density that is an unit exponential function of the radius according to $$\rho(r)=1/\rho_0 e^{-\rho_0 r}$$

In [ ]:
# TODO: Implement exponential_density(x, y, z, rho0=1.0) returning exp(-rho0*r)/rho0

# TODO: Calculate mass_exp and unc_exp using monte_carlo_integration with N

# TODO: Create convergence comparison plot vs N,  set theoretical value for comparison

# Part II: Ising Model (4 pt)

**Statistical Mechanics Background:**

The **Ising model** is a mathematical model of ferromagnetism in statistical mechanics. It describes a system of discrete spins that can be in one of two states (+1 or -1) arranged on a lattice.

**Physical Motivation:**
- Models magnetic materials like iron
- Each lattice site represents an atomic magnetic moment
- Spins prefer to align with neighbors (ferromagnetic coupling)
- Temperature creates thermal fluctuations that oppose ordering
- Results in **phase transition** between ordered and disordered states

**Energy Function:**
$$H(S)=-\frac{J}{2}\sum_{i,j} s_{i,j} (s_{i+1,j}+s_{i-1,j}+s_{i,j+1}+s_{i,j-1})$$

Where:
- **J > 0**: Ferromagnetic coupling (favors parallel spins)
- **⟨i,j⟩**: Sum over nearest neighbors only
- **s_i ∈ {-1, +1}**: Spin values

Without loss of generizability, we choose a parameterization that $J=1$ and $k_B=1$.

**Key Physics:**
- **Low T**: Thermal energy << J → spins align → ordered (ferromagnetic) phase
- **High T**: Thermal energy >> J → spins random → disordered (paramagnetic) phase  
- **Critical temperature T_c**: Phase transition occurs
- **2D Ising exact result**: T_c = 2J/ln(1+√2) ≈ 2.269 (for J=1)

**Metropolis Algorithm:**
Uses Monte Carlo sampling to generate configurations according to Boltzmann distribution:
P(configuration) ∝ $e^{-\Delta E/T}$, with $T=1.5$.

**Algorithm Steps:**
1. Choose random spin
2. Calculate energy change ΔE if flipped  
3. Accept flip with probability min(1, exp(-ΔE/T))
4. Repeat many times to reach equilibrium


## Step 1: Initialize Lattice

**Lattice Setup:**
- 10×10 lattice with periodic boundaries (edges wrap around)
- Initial state: all spins = +1
- Each spin has exactly 4 neighbors

In [ ]:
# TODO: Initialize 10x10 lattice with all spins = +1
# Use np.ones((L, L), dtype=int) for integer spins

# TODO: Test lattice creation and print shape and initial magnetization

## Step 2: Energy Calculation

**Energy Function:** E = -J Σ s_i s_j (sum over nearest neighbors)

**Key Points:**
- Parallel spins (+1,+1 or -1,-1): contribute -J (lower energy)
- Antiparallel spins (+1,-1): contribute +J (higher energy)  
- Use periodic boundaries: neighbors wrap around edges
- Avoid double-counting pairs

**Test if your energy function is correct:**

for a Test lattice (3x3):

[[1 1 1]
 [1 1 1]
 [1 1 1]]
 
Total energy: -18.0

In [ ]:
# TODO: Calculate total energy from 4 neighbor coordinates (avoid double counting!)
# Count each pair once: only right and down neighbors

# TODO: Energy change if spin (i,j) flips
# ΔE = -2 × local_energy (since spin changes sign)

# TODO: Test your energy function with small lattice and print results 

## Step 3: Metropolis Algorithm: Magnetization vs. N

Calculate the magnitization $$<M>=\frac{1}{N} \sum_{i,j\in\Lambda} s_{i,j}$$ as function of MC steps $N$. Plot $<M>$ as function of $N$ where $N$ starts from 0 to 10000 with step size $\Delta N=100$. Does the magnitization converge to an equillibrium value?

**Algorithm:**
1. Choose random spin
2. Calculate energy change ΔE if flipped
3. Accept flip with probability min(1, exp(-ΔE/T))
4. Repeat for N times

**Important Grading requirement:**
> **💡 Note:** This MC algorithm is partially given, but you need to explain what each line stands for.


In [ ]:
# TODO: Implement Metropolis algorithm

# TODO: Monte Carlo sweep (L² attempts) using Metropolis algorithm 
# Perform L² individual spin flip attempts, return updated configuration

# def MCmove(config, T):
#     for i in range(L):
#         for j in range(L):
#                 a = np.random.randint(0, L)
#                 b = np.random.randint(0, L)
#                 spin =  config[a, b]
#                 neighbors = config[(a+1)%L,b] + ... # its 4 neighbors
#                 delE = 2*spin*neighbors # Explain why
#                 if delE < 0:
#                     spin *= -1
#                 elif rand() < np.exp(-delE/T): # What are we doing here?
#                     spin *= -1
#                 config[a, b] = spin
#     return config

# TODO: Full simulation with observable measurement
# Run multiple sweeps (MC steps), sample magnetization and energy every few sweeps

# TODO:Plot average Magnetization as function of N (number of MC steps)

# plt.scatter(Steps, M_avg, s=50, marker='o', color='RoyalBlue')
# plt.xlabel('N (T = {:.2f})'.format(T), fontsize=20); 
# plt.ylabel("Magnetization ", fontsize=20); 

## Bonus 2: Temperature Study (4 pt)

**Goal:** Observe ferromagnetic phase transition in physics observables around T_critical= 2.0 / np.log(1 + np.sqrt(2))


**Method:**
- Study temperatures $T$ from 1.5 to 3.25 with 10 steps.
- For each T: equilibrate with 10000 MC sampling → measure → record averages 
- Plot Magnetization, Energy, Susceptibility, Heat capacity vs. temperature

**Expected:** 
- Low T: high |m|, low energy (ordered)
- High T: low |m|, high energy (disordered)
- Transition around T_c = 2.269

**Observable Quantities:**
- **Magnetization**: $\langle m \rangle = \frac{1}{N_{steps}} \sum_{i=1}^{N_{steps}} M_i$ (order parameter) - measures degree of spin alignment
- **Energy**: $\langle e \rangle = \frac{1}{N_{steps}} \sum_{i=1}^{N_{steps}} E_i$ (average energy per spin) - indicates thermal state of the system
- **Susceptibility**: $\chi = \frac{1}{k_B T}(\langle M^2 \rangle - \langle M \rangle^2) = \frac{1}{T}\left(\frac{1}{N_{steps}}\sum_{i=1}^{N_{steps}} M_i^2 - \left(\frac{1}{N_{steps}}\sum_{i=1}^{N_{steps}} M_i\right)^2\right)$ - measures response to external magnetic field, peaks at phase transition
- **Heat capacity**: $C = \frac{1}{k_B T}(\langle E^2 \rangle - \langle E \rangle^2) = \frac{1}{T}\left(\frac{1}{N_{steps}}\sum_{i=1}^{N_{steps}} E_i^2 - \left(\frac{1}{N_{steps}}\sum_{i=1}^{N_{steps}} E_i\right)^2\right)$ - quantifies energy fluctuations, shows anomaly at critical temperature

*Note that we have chosen $k_B=1$ for this exercise*

In [ ]:
# TODO: Scan temperatures from 1.5 to 3.25 with 10 steps
# Loop over temperatures: equilibrate, measure, record averages

# TODO: Create 4 plots: magnetization vs T, energy vs T, Susceptibility vs T, Specifc Heat vs T
# Add vertical line at theoretical T_c 

# TODO: Print relative difference between empirical and theoretical T_c
# print(f"Relative difference: {abs(T_empirical - T_critical)/T_critical * 100:.1f}%")

# Discussion

**Answer the following questions based on your results:**

## Part I: MC Integration

1. What was your theoretical mass for uniform density and linear density (and exponential density if you did bonus)?
2. How fast did MC integration converge to $1\%$ error for each density distribution?
2. Does the uncertainty scale as expected?

## Part II: Ising Model  
1. What critical temperature did you observe? Compare your T_c with theoretical value (2.269).

## Submission Instructions

> **📋 Important Notice:** When you have completed all sections of this lab, please download your notebook as an HTML file for submission on Canvas.
> 
> **To download as HTML:**
> 1. Go to **File** → **Download as** → **HTML (.html)**
> 2. Save the file with a descriptive name (e.g., `Lab3_YourName.html`)
> 3. Upload the HTML file to the corresponding Canvas assignment
> 
> Make sure all cells have been executed and all outputs are visible before downloading!